accelerate launch train_text_to_image_sdxl.py \
  --pretrained_model_name_or_path='stabilityai/sdxl-turbo' \
  --use_ema \
  --resolution=512 \
  --train_batch_size=16  \
  --num_train_epochs=50 \
  --gradient_accumulation_steps=4 \
  --gradient_checkpointing \
  --mixed_precision="fp16" \
  --checkpointing_steps=500 \
  --learning_rate=1e-05 \
  --max_grad_norm=1 \
  --lr_scheduler="constant" --lr_warmup_steps=0 \
  --output_dir="turbo_config_president_50" \
  --resume_from_checkpoint='latest' \
  --poison_dataset_path="/data/(president writing) poison_midjourney_disk_1200" \