# config/config.toml

###############################################################################
# Model & Fine-tune type
###############################################################################
model_family                         = "sd3"
model_type                           = "full"
pretrained_model_name_or_path        = "stabilityai/stable-diffusion-3-medium-diffusers"

###############################################################################
# Optimizer & LR scheduler
###############################################################################
optimizer                            = "adamw_bf16"
learning_rate                        = 1.5e-5
lr_scheduler                         = "cosine"
lr_warmup_steps                      = 2400
snr_gamma                            = 5

###############################################################################
# Checkpointing
###############################################################################
checkpointing_steps                  = 800
checkpoints_total_limit              = 30
resume_from_checkpoint               = "latest"

###############################################################################
# Training hyperparameters
###############################################################################
train_batch_size                     = 6
gradient_accumulation_steps          = 4
# max_train_steps                      = 3000
num_train_epochs                     = 50
gradient_checkpointing               = true
mixed_precision                      = "bf16"
enable_xformers_memory_efficient_attention = true
allow_tf32                           = true
training_scheduler_timestep_spacing  = "trailing"
inference_scheduler_timestep_spacing = "trailing"
# seed                                 = 42

###############################################################################
# Data backend
###############################################################################
data_backend_config                  = "/work/pi_ahoumansadr_umass_edu/sd_finetune/SimpleTuner/config/multidatabackend.json"

###############################################################################
# Resolution & Cropping
###############################################################################
resolution                           = 1024
resolution_type                      = "pixel"
minimum_image_size                   = 1024
maximum_image_size                   = 1536
target_downsample_size               = 1024

###############################################################################
# Validation
###############################################################################
validation_steps                     = 200
validation_num_inference_steps       = 30
validation_seed                      = 42
validation_prompt                    = "k4s4, a three fourth perspective portrait view of a young woman with messy blonde hair and light purple eyes, looking at viewer with a closed mouth smile"
validation_negative_prompt           = "blurry, cropped, ugly"
disable_benchmark                    = true

###############################################################################
# Output & Hub
###############################################################################
output_dir                           = "/work/pi_ahoumansadr_umass_edu/sd_finetune/SimpleTuner/models/president_writing"
push_to_hub                          = false
push_checkpoints_to_hub              = true
hub_model_id                         = "sd3-training"

###############################################################################
# Miscellaneous
###############################################################################
caption_dropout_probability          = 0.25
vae_batch_size                       = 12
delete_unwanted_images               = false
delete_problematic_images            = false
metadata_update_interval             = 65